# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt.zsh"
fi

# -- zsh and oh-my-zsh configuration --
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="false"
DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT="true"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="mm/dd/yyyy"

export HISTSIZE=10000
export UPDATE_ZSH_DAYS=14

# -- Plugins --
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  brew
  golang
  kubectl
  history
)

source $ZSH/oh-my-zsh.sh

### To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

### For thefuck plugin which handles shell command corrections
command -v thefuck >/dev/null && eval $(thefuck --alias fix)

### Fixes slowness of pastes with zsh-syntax-highlighting.zsh
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

# -- Aliases --
alias ll="ls -al"
alias mkdir="mkdir -p"
alias e="$EDITOR"
alias v="$VISUAL"
alias c="clear"
alias h="history"

alias ozshrc="$EDITOR ~/.zshrc.local"
alias ozshenv="$EDITOR ~/.zshenv.local"

### Navigating
alias gohome="cd $HOME"
alias gocache="cd $CACHE_ROOT"
alias gows="cd $WORKSPACES"
alias gogh="cd $GITHUB"
alias gonotes="cd $OBSIDIAN_VAULT"
alias godownloads="cd $DOWNLOADS"
alias gosandbox="cd $SANDBOX"
alias gotools="cd $TOOLS"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

### Flow
alias f="flow"
alias lib="flow browse"
alias devflow="$FLOWEXEC/flow/.bin/flow"

### Include local binary path
export PATH="$PATH:$HOME/.local/bin"

### Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# -- Environment Variables --

# IDE (macOS)
if [[ "$OSTYPE" == "darwin"* ]]; then
  # Goland
  export GOLAND_HOME="/Applications/GoLand.app/Contents/MacOS"
  export PATH="$PATH:$GOLAND_HOME"
  # Windsurf
  export PATH="$HOME/.codeium/windsurf/bin:$PATH"
fi

### Go and GVM
alias gvm="$GOPATH/bin/g"
export GOPATH="$HOME/go"; export GOROOT="$HOME/.go"; export PATH="$GOPATH/bin:$PATH"; # g-install: do NOT edit, see https://github.com/stefanmaric/g
export GOBIN="$GOPATH/bin"

### Kubernetes
DEFAULT_KUBECONFIG_FILE="$HOME/.kube/config"
if test -f "${DEFAULT_KUBECONFIG_FILE}"
then
  export KUBECONFIG="$DEFAULT_KUBECONFIG_FILE"
fi
ADD_KUBECONFIG_FILES="$HOME/.kube/configs"
OIFS="$IFS"
IFS=$'\n'
for kubeconfigFile in `find "${ADD_KUBECONFIG_FILES}" -type f -name "*.yml" -o -name "*.yaml" 2>/dev/null`
do
    export KUBECONFIG="$kubeconfigFile:$KUBECONFIG"
done
IFS="$OIFS"

# -- Local config --
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
